name: golang check

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: go test engine
        run: |
          set -x
          cd engine
          go test ./...

      - name: go test expr
        run: |
          set -x
          cd expression
          go test ./...

      - name: check gox
        run: |
          set -x
          cd gox
          go build -o test

      - name: check poc-runner
        run: |
          set -x
          cd cmd
          go build -o test
